version: '3.4'

services:
  criticine-prod:
    networks:
      - nginx_default
    ports:
      - '${PORT_PROD}:3000'
    container_name: criticine-prod
    image: '${PROD_TAG}'
    build:
      context: .
      dockerfile: dockerfile
      target: prod
networks:
  nginx_default:
    external: true
