version: '3.4'

services:
  criticine-staging:
    networks:
      - nginx_default
    # No need to expose a port as container will be behind reverse proxy
    container_name: criticine-staging
    image: lucas2708/criticine:staging
    build:
      context: .
      dockerfile: dockerfile
      target: prod
      args:
        - NODE_ENV=staging
networks:
  nginx_default:
    external: true
