version: '3.4'

services:
  criticine-dev:
    ports:
      - '3000:3000'
    container_name: criticine-dev
    image: criticine:dev
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: dockerfile
      target: dev
      args:
        - NODE_ENV=development
    network_mode: 'bridge'
