version: '3.4'

services:
  criticine-prod:
    networks:
      - nginx_default
    ports:
      - '${PORT_PROD}:3000'
    container_name: criticine-prod
    image: lucas2708/criticine:production
    build:
      context: .
      dockerfile: dockerfile
      target: prod
      args:
        - NODE_ENV=production
networks:
  nginx_default:
    external: true
