name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  test:
    if: github.event_name == 'pull_request'
    name: Test
    uses: Luccas27/pipelines/.github/workflows/test.yml@main
    permissions:
      actions: read
      contents: read
      security-events: write
  build-staging:
    if: github.event_name == 'pull_request'
    name: Build Staging
    needs: test
    uses: Luccas27/pipelines/.github/workflows/build.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
      GPG_PUBLIC_KEY: ${{secrets.GPG_PUBLIC_KEY}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
    with:
      docker_image_tag: lucas2708/criticine:staging
  manual-approval-staging:
    if: github.event_name == 'pull_request'
    name: Approve Staging
    environment: Staging
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs:
      - test
      - build-staging
    steps:
      - run: echo 'Approval for Staging deployment'
  deploy-staging:
    if: github.event_name == 'pull_request'
    name: Deploy Staging
    needs: manual-approval-staging
    uses: Luccas27/pipelines/.github/workflows/deploy.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
      GPG_PUBLIC_KEY: ${{secrets.GPG_PUBLIC_KEY}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
      SSH_HOST: ${{secrets.SSH_HOST}}
      SSH_KEY: ${{secrets.SSH_KEY}}
      SSH_USER: ${{secrets.SSH_USER}}
      SSH_PORT: ${{secrets.SSH_PORT}}
    with:
      dockercompose_filename: docker-compose.staging.yml
  build-prod:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Build Production
    uses: Luccas27/pipelines/.github/workflows/build.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
      GPG_PUBLIC_KEY: ${{secrets.GPG_PUBLIC_KEY}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
    with:
      docker_image_tag: lucas2708/criticine:latest
  manual-approval-prod:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Approve Prod
    environment: Production
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs:
      - build-prod
    steps:
      - run: echo 'Approval for Production deployment'
  deploy-prod:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Deploy Production
    needs: manual-approval-prod
    uses: Luccas27/pipelines/.github/workflows/deploy.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
      GPG_PUBLIC_KEY: ${{secrets.GPG_PUBLIC_KEY}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
      SSH_HOST: ${{secrets.SSH_HOST}}
      SSH_KEY: ${{secrets.SSH_KEY}}
      SSH_USER: ${{secrets.SSH_USER}}
      SSH_PORT: ${{secrets.SSH_PORT}}
    with:
      environment: Production
      dockercompose_filename: docker-compose.prod.yml
