name: Production

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    name: Build Prod
    uses: Luccas27/pipelines/.github/workflows/build.yml@main
    with:
      node_env: production
      app_name: criticine
    secrets:
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
      GPG_PUBLIC_KEY: ${{secrets.GPG_PUBLIC_KEY}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}

  deploy:
    name: Deploy Prod
    uses: Luccas27/pipelines/.github/workflows/deploy.yml@main
    needs: [build]
    with:
      dockercompose_filename: docker-compose.prod.yml
      environment: Production
    secrets:
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
      SSH_HOST: ${{secrets.SSH_HOST}}
      SSH_USER: ${{secrets.SSH_USER}}
      SSH_KEY: ${{secrets.SSH_KEY}}
      SSH_PORT: ${{secrets.SSH_PORT}}
