name: Staging

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches: ['main']
  workflow_dispatch:
jobs:
  test:
    name: Test
    uses: Luccas27/pipelines/.github/workflows/test.yml@main

  code-ql:
    name: Vulnerability scan
    uses: Luccas27/pipelines/.github/workflows/code-ql.yml@main
    needs: test
    permissions:
      actions: read
      contents: read
      security-events: write

  build:
    name: Build Staging
    uses: Luccas27/pipelines/.github/workflows/build.yml@main
    needs: [test, code-ql]
    with:
      node_env: staging
      app_name: criticine
    secrets:
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
      GPG_PUBLIC_KEY: ${{secrets.GPG_PUBLIC_KEY}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}

  deploy:
    name: Deploy Staging
    uses: Luccas27/pipelines/.github/workflows/deploy.yml@main
    needs: [test, build, code-ql]
    with:
      dockercompose_filename: docker-compose.staging.yml
      environment: Staging
    secrets:
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
      SSH_HOST: ${{secrets.SSH_HOST}}
      SSH_USER: ${{secrets.SSH_USER}}
      SSH_KEY: ${{secrets.SSH_KEY}}
      SSH_PORT: ${{secrets.SSH_PORT}}
